[project]
name = "graphql-lambda"
version = "0.1.0"
description = "API to run GraphQL queries on AWS Lambda"

readme = "README.md"
requires-python = ">=3.12.7"

dependencies = [

]


[dependency-groups]
dev = [
    # Specific to this template


    # Managed by upstream template
    "pyright>=1.1.391",
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
    "pytest-randomly>=3.16.0",
]

[tool.uv]
package = true
